language: go
go:
  - '1.4'
  - tip

install:
  - ln -s $PWD $GOPATH/src/sendgrid-cli
  - go get -d ./...

script:
  - go build -o sendgrid-cli
  - ls -al
  - ./sendgrid-cli -d  -U $SENDGRID_USER -P $SENDGRID_PASSWORD -s TEST_v2 -t E$RANDOM@mailinator.com -a attachment.jpg "<strong>TEST MESSAGE</strong>"
  - ./sendgrid-cli -d  -k $SENDGRID_API_KEY -s "TEST v3" -t E$RANDOM@mailinator.com -a attachment.jpg "<strong>TEST MESSAGE</strong>"
