language: go
go:
  - '1.3'
  - tip

install:
  - go get -d ./...
  - go install

script:
  - sendgrid-cli -d  -U $SENDGRID_USER -P $SENDGRID_PASSWORD -s TEST_v2 -t E$RANDOM@mailinator.com -a attachment.jpg "<strong>TEST MESSAGE</strong>"
  - sendgrid-cli -d  -k $SENDGRID_API_KEY -s TEST_v3 -t E$RANDOM@mailinator.com -a attachment.jpg "<strong>TEST MESSAGE</strong>"
